# Peppermint YARP Reverse-Proxy docker compose example
version: '3.8'

services:
  reverseproxy:
    image: alexandrejulien/peppermint-reverseproxy
    container_name: peppermint-reverseproxy
    volumes:
    - ./appsettings.json:/app/appsettings.json
  webapp:
     image: dockersamples/static-site
     container_name: webapp
     ports:
     - "8080:8080"
