name: Release-Docker
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Peppermint.ReverseProxy.sln
    - name: Build Portable
      run: dotnet build ./Peppermint.ReverseProxy.sln --no-restore --configuration Release
    - name: Publish Portable
      run: dotnet publish src/Peppermint.ReverseProxy/Peppermint.ReverseProxy.csproj  -o app/Portable
    - name: Upload a Build Artifact all platforms
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Peppermint.ReverseProxy-portable
        path: app/Portable
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        file: src/Peppermint.ReverseProxy/Dockerfile
        push: true
        tags: |
          alexandrejulien/peppermint-reverseproxy:latest
          alexandrejulien/peppermint-reverseproxy:${{ github.ref_name }}

        

