name: Release

on:
  push:
    branches: [ "main", "feature/release-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Portable
      run: dotnet build --no-restore --configuration Release
    - name: Publish Win x86
      run: dotnet publish src/Peppermint.ReverseProxy/Peppermint.ReverseProxy.csproj --runtime win-x86 --self-contained true -o app/Winx86
    - name: Publish Linux
      run: dotnet publish src/Peppermint.ReverseProxy/Peppermint.ReverseProxy.csproj --runtime linux-x64 --self-contained true -o app/Linuxx64
    - name: Publish MacOS
      run: dotnet publish src/Peppermint.ReverseProxy/Peppermint.ReverseProxy.csproj --runtime osx-x64 --self-contained true -o app/MacOS
    -
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Peppermint.ReverseProxy
        path: app
        

